
spring:
  datasource:
    url: "jdbc:postgresql://127.0.0.1:15432/inventory"
    username: postgres
    password: password
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:liquibase/changelog-master.xml
  redis:
    host: localhost
    port: 6379
    ttl: 1800

springdoc:
  packages-to-scan: com.intergamma
  #  use-management-port: true
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui-custom.html
    enabled: true
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: true
server:
  port: 7070


intergamma:
  api:
    name: intergamma-inventory-api
    cors:
      addAllowedOrigin: http://localhost:4200


